language: cpp
sudo: required
os:
- linux
- osx
env:
  global:
  - LINUX_PICKLE_URL=https://www.dropbox.com/s/yclmzq1n63cminb/linux-pickle.tar.gz?dl=0
  - OSX_PICKLE_URL=https://www.dropbox.com/s/m23s3l9g1s9yw87/osx-pickle.tar.gz?dl=0
before_script:
# To help prevent timeouts, download a 'pickled' .tar.gz archive of the linux
# webrtc checkout. LINUX_PICKLE_URL was created with:
# `GZIP=-9 tar zcvf linux-pickle.tar.gz .`
- mkdir out
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -qO- $LINUX_PICKLE_URL | tar xz
  -C `pwd`/out; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -qO- $OSX_PICKLE_URL | tar xz -C
  `pwd`/out; fi
script:
- ./build.sh -n Release -d
