language: cpp
sudo: required
os:
- linux
- osx
env:
  global:
  - LINUX_PICKLE_URL=https://www.dropbox.com/s/yclmzq1n63cminb/linux-pickle.tar.gz?dl=0
  - OSX_PICKLE_URL=https://www.dropbox.com/s/m23s3l9g1s9yw87/osx-pickle.tar.gz?dl=0
before_script:
# Update the default 'trusty' linker version for tests to link and pass.
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  sudo apt-get install -y binutils-2.26 && sudo update-alternatives --install
  /usr/bin/ld ld /usr/lib/binutils-2.26/bin/ld 90; fi
# To help prevent timeouts, download a 'pickled' .tar.gz archive of the linux
# webrtc checkout. LINUX_PICKLE_URL was created with:
# `GZIP=-9 tar zcvf linux-pickle.tar.gz .`
- mkdir -p out
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_retry curl -L $LINUX_PICKLE_URL -o pickle.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_retry curl -L $OSX_PICKLE_URL -o pickle.tar.gz; fi
- tar xzf pickle.tar.gz -C out && rm pickle.tar.gz
script:
- ./build.sh -n Release -d
- test/run_tests.sh $(ls -d -1 out/webrtc*/) Release
# Allow failures on osx until the travis osx pipeline is more robust.
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
